# Generated by Django 5.1.15 on 2026-08-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
